'https://plantuml.com/sequence-diagram'
@startuml
left to right direction
skinparam packageStyle rectangle
actor Customer
actor Manager
rectangle Parkhaus {
  Customer -- (checkout)
  (checkout) .> (payment) : <<include>>
  (help) .> (checkout) : <<extend>>
  (checkout) -- Manager
}
@enduml